### ISSUE TITLE
PUT_SPRING - fails using mpirun

### ISSUE THREAD

**Issue by bencannell** [parmes/solfec#78] opened 2018-09-04 17:08 UTC
Hi @tkoziara,

I hope you are well!

We're looking into using the PUT_SPRING command in solfec. Based on some initial tests, this command seems to fail when running using solfec-mpi (behaviour is expected using solfec non-mpi). Have you tested this functionality successfully using solfec-mpi?

See stdout/stderr output attached:

[mpirun-PUT_SPRING-fail.log](https://github.com/tkoziara/solfec/files/2349520/mpirun-PUT_SPRING-fail.log)

I'll try and get a helpful example over to you tomorrow.

Many thanks,

Ben

(FYI @stevebrasier)

**Comment by tkoziara** [comment] 2018-09-28 12:16
Hi Ben; PUT_SPRING has indeed been troublesome in parallel; I remember some reports; An example would be welcome; In the meantime, I'll try to produce an example of my own. Tomek

**Comment by tkoziara** [comment] 2018-09-28 13:09
Indeed, having created [this example](https://github.com/tkoziara/solfec/blob/9eebe7748b95d5e0d6b141896e0a37c422366af2/inp/devel/put_spring_mpi.py) and running serial, and -np 2, -np 4 parallel, I can see that there is some instability due to - I am guessing - incorrect passing of spring parameters or callback data across MPI ranks; See pictures below:
<img width="200" alt="put_spring_mpi_ 78" src="https://user-images.githubusercontent.com/2198068/46210088-0daba780-c330-11e8-9208-106b5f8e5fdd.png">
There are 4 ranks in this case and there have been some switching of constraints between ranks prior this time. Some of the springs begin to stretch without limits as if springs had zero stiffness. This is a little different behaviour than in your case, where the spring callback failed altogether, but the root cause of the problem may be common to both symptoms. I'll continue having look.

**Comment by tkoziara** [comment] 2018-10-01 10:39
Ben, I fixed this issue (see a7ab341); please let know whether it resolved the problem on your end; T.

**Comment by bencannell** [comment] 2018-10-12 12:56
Hi @tkoziara,

Thank you for this. However, the fix doesn't seem to have resolved my issue.

I will email you my test case.

Thanks,

Ben

**Comment by bencannell** [comment] 2019-01-10 09:46
Hi @tkoziara, I've just sent a test case to your personal email address. Thanks!

**Comment by tkoziara** [comment] 2019-01-11 11:46
Ben, this issue is now fixed by adding the [REGISTER_BASE](https://parmes.org/solfec/user/utilities.html#register-callback) command to your input file. I am closing the issue. As always feel free to reopen if needed.

**Closed by tkoziara** 2019-01-11 11:46 UTC
Labels: bug
