### ISSUE TITLE
run mpi does not work

### ISSUE THREAD

**Issue by nicolasmecamas** [parmes/solfec#59] opened 2017-04-10 20:07 UTC
Hello developer,
I used solfec to simulate a castest and I saw that the following macro commands do not work with mpi/ Could you please helps me to debug them?
1. -	Macro commade FIX_POINT() 
2.-	Macro commade PUT_RIGID_LINK() 
3. -	Macro commade PUT_SPRING() 
Thank you for your help.
Nicolas

**Comment by tkoziara** [comment] 2017-04-11 06:31
Hi Nicolas,
Please attach a shortest possible input file that reproduces this issue;
Thank you,
Tomek

**Comment by nicolasmecamas** [comment] 2017-04-13 14:37
Hi Tomek,
Could you find enclosed three tests FIX_POINT.py  ​PUT_RIGID_LINK.py  ​ ​PUT_SPRING.py. 
I ran mpi with these tests as follows:
mpirun -np 4 solfec-mpi -s Test_mpi ​FIX_POINT.py
mpirun -np 4 solfec-mpi -s Test_mpi ​PUT_RIGID_LINK.py ​

mpirun -np 4 solfec-mpi -s Test_mpi PUT_SPRING.py

The FIX_POINT.py works but it does not give a good result. The two others does not work.


Thank Tomek

[FIX_POINT.py.docx](https://github.com/tkoziara/solfec/files/919965/FIX_POINT.py.docx)
[PUT_RIGID_LINK.py.docx](https://github.com/tkoziara/solfec/files/919964/PUT_RIGID_LINK.py.docx)
[PUT_SPRING.py.docx](https://github.com/tkoziara/solfec/files/919963/PUT_SPRING.py.docx)

**Comment by nicolasmecamas** [comment] 2017-04-15 16:57
Hi Tomek,
You must change the files from "...py.docx" to "...py" to read the files
Thank,
Nicolas

**Comment by tkoziara** [comment] 2017-04-19 10:23
Hi Nicolas,
Thank you for spotting this; This is related to this functionality not being updated after implementation of the so called "local body storage" (the LOCAL_BODIES = yes flag inside of Config.mak); I am looking into this:)
Tomek

**Comment by tkoziara** [comment] 2017-04-20 14:44
Hi Nicolas,
I have initially fixed this issue with today's commit; Please updated your sources and recompile solfec-mpi to test this; All now seems to be working, except:

mpirun -np 2 solfec-mpi PUT_SPRING.py

becomes unstable at some point (use -s 0.00001 to see all solver output) and fails; this is not the case for other numbers of MPI ranks (any -np > 2); I looked at this but could not find our a particular reason for this; Also this does not occur when you use GAUSS_SEIDEL_SOLVER, but persists when you use NEWTON_SOLVER and set a higher accuracy; this has something to do with propagation of a small perturbation of the system after bodies and constraints have been moved between ranks during load balancing;

Once you confirm that the remaining cases work well, I think we could register the PUT_SPRING -np 2 instability as a separate issue (since it may have a different origin), and close the current one;

Best regards,
Tomek

**Comment by nicolasmecamas** [comment] 2017-05-05 09:03
I updated the new version and recomplie solfec-mpi. But it generated again the following errors:

Macro commande : PUT_SPRING   =>  NOOK, NOT RUN NOOK
peter@peter:~/PUT_SPRING$ mpirun -np 4 solfec_new-mpi PUT_SPRING.py 
^Cmpirun: killing job...

Macro commande : PUT_RIGID_LINK      =>  NOOK, NOT RUN
peter@peter:~/PUT_RIGID_LINK$ mpirun -np 2 solfec_new-mpi PUT_RIGID_LINK.py 
^Cmpirun: killing job...



Macro commande : FIX_POINT      =>  NOOK, RUN nhung ko co  fix point
peter@peter:~/FIX_POINT$ mpirun -np 2 solfec_new-mpi FIX_POINT.py

**Comment by tkoziara** [comment] 2017-05-05 10:31
Yes; I am experiencing problem with running these examples myself; Perhaps some of the recent changes reactivated this; Let me have another look;

**Comment by tkoziara** [comment] 2017-05-09 08:18
Nicolas: please try the most recent version; when working on something else I produced a memory related bug which was causing this; let me know whether now it works for you; Tomek

**Comment by nicolasmecamas** [comment] 2017-06-02 12:47
Hi Tomek,
I have updated the newer version but It does not work either (see attached file mpi.docx)
[MPI.docx](https://github.com/tkoziara/solfec/files/1047677/MPI.docx)
Could you please take a look to it?
Thank you in advance,
Nicolas

**Comment by tkoziara** [comment] 2017-06-05 07:22
Nicolas,
What kind of file did you attach as MPI.docx? This is a binary file and I don't know how to use it.
I just checked and all three initially provided examples work on my computer - I run:
``mpirun -np 3 solfec-mpi EXAMPLE.py`` in each case and all terminated fine; Can you try to run those examples like that and show me the contents of your console?
Tomek

**Comment by tkoziara** [comment] 2017-06-05 07:26
OK, wait, I can see that this is simple a Word document -- and not something renamed as a Word document:) I am looking at it...

**Comment by tkoziara** [comment] 2017-06-05 09:22
Testing it on [VBOX](http://parmes.github.io/vbox) I noticed that those tests seem to work when ``DEBUG = yes`` is set up in ``Confg.mak`` and they get stuck when ``DEBUG = no`` is used; This is also confirmed on my Mac laptop; For the moment I don't see why there should be such difference - I am still looking at it...

In the meantime you can try running when solfec-mpi is compiled using ``DEBUG = no`` and tell me whether this also works for you;

**Comment by tkoziara** [comment] 2017-06-06 09:41
Hi Nicolas,
It looks like the global -O3 optimisation level was affecting a correct execution of a fragment of code with many loops and pointer operations when compiled with GCC; I have  locally decreased the level of optimisation for this bit of code (see [this commit](https://github.com/tkoziara/solfec/commit/a1fc56abc71735b1ed24037a42f18113d5fbb311)) and it worked OK for me; Let me know whether this has resolved the issue for you as well.
Best regards,
Tomek

**Comment by nicolasmecamas** [comment] 2017-06-07 15:33
Hi Tomek,
I have updated ne newer version. It works now for FIX_POINT() and PUT_RIGID_LINK() operator with mpi.  But not yet work for  for PUT_SPRING() operator, it generates the same error:
Could you please take a look?
Thank you in adavance,
Nicolas

Peter@linux:​/Works/Debugs/mpi/PUT_SPRING$​ mpirun -np 4 solfec-mpi PUT_SPRING_2_sphere-RIG.py

Traceback (most recent call last):

File "<string>", line 1, in <module>

File "PUT_SPRING_2_sphere-RIG.py", line 22, in <module>

   FORCE (bod_sphere2, 'SPATIAL', Nref2, (0, 0, -1),F)

TypeError: 'point' must be a tuple object

WARNING solfec.c: 295 => input parsing error

Traceback (most recent call last):

File "<string>", line 1, in <module>
File "PUT_SPRING_2_sphere-RIG.py", line 22, in <module>
FORCE (bod_sphere2, 'SPATIAL', Nref2, (0, 0, -1),F)
TypeError: 'point' must be a tuple object
WARNING solfec.c: 295 => input parsing error
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "PUT_SPRING_2_sphere-RIG.py", line 22, in <module>
FORCE (bod_sphere2, 'SPATIAL', Nref2, (0, 0, -1),F)
TypeError: 'point' must be a tuple object
WARNING solfec.c: 295 => input parsing error

**Comment by tkoziara** [comment] 2017-06-08 11:00
Please attach: PUT_SPRING_2_sphere-RIG.py
I don't have it.

**Comment by tkoziara** [comment] 2017-06-12 08:25
Hi:)
This must be the same file as for [issue 66](https://github.com/tkoziara/solfec/issues/66)?
Here is my modification: [PUT_SPRING_2_sphere-RIG-v1.1.zip](https://github.com/tkoziara/solfec/files/1067417/PUT_SPRING_2_sphere-RIG-v1.1.zip)
[See also the explanation there](https://github.com/tkoziara/solfec/issues/66#issuecomment-307721555); Let me know whether this issue can now be closed;
Tomek

**Comment by tkoziara** [comment] 2019-01-15 11:06
@nicolasmecamas I am closing this issue assuming that it is no longer relevant.

**Closed by tkoziara** 2019-01-15 11:06 UTC
Labels: bug
